import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
// import { Inter } from "next/font/google";
import { CounterProvider } from "./components/Context";

import type { Metadata } from "next";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import NavBar from "./components/NavBar";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body /*className={inter.variable}*/>
        <Theme accentColor="violet">
          <NavBar />
          <main className="p-5">
            <CounterProvider>
              <Container>{children}</Container>
            </CounterProvider>
          </main>
        </Theme>
      </body>
    </html>
  );
}
